#+title: Voice of the Customer for Water Utilities

This project is provides open source book about methods to measure the /Voice of the customer/ (Voc) in water utilities. This project includes:

- Book (Source files in Emacs Org mode)
- Case study data sets (synthetic and actual)
- Scripts analysing the case study data (R language for statistical computing)

* Voice of the Customer Book
This book is written in [[https://github.com/pprevos/emacs-writing-studio][Emacs Org mode format]], the R language for statistical computing to generate and analyse data, and create visualisations and GraphViz for graphics. When completed, it wil be published as an ebook and paperback and made available through your favourite book seller (except for Amazon because they don't allow open source books).

The Org mode source files to generate the book versions are available in this repository. Note that these are early drafts of the text as this is a work in progress:

1. [[file:01-voc-introduction.org][Introduction]]
2. [[file:02-voc-qualitative-data-science.org][Introduction to Qualitative Data Analysis]]
3. [[file:03-voc-text-analysis.org][Principles of Compuational Text Analysis]]
4. [[file:04-voc-sentiment-analysis.org][Extracting Sentiments]]
5. [[file:05-voc-topic-analysis.org][Analysing Topics]]
6. [[file:06-voc-surveys.org][Quantitative Surveys]]
7. [[file:07-voc-indirect.org][Indirect Voice of the Customer Measurement]]
8. [[file:08-voc-implementation.org][Synthesis]]

To create an ebook from the plain text files and images you need to use Emacs and the Emacs Writing Studio configuration. It will also require LaTeX (for formulas and PDF versions), the R language and GraphViz.

* Directories
- =book=: Files to generate the book (bibliography)
- =data=: Case study synthetic data files. This data was collected from public sources or synthesised using statistical methods and Large Language Models.
- =images=: Book illustrations. All images in this repository were created by the author or generated using code.
- =scripts= directory contains scripts for the case studies used in this book. All scripts are written in the Tidyverse dialect of the R language for statistical computing.

* License and Copyright
** Code
All code is licensed under the GNU General Public License (version 3). This license grants four basic freedoms:

- The freedom to run the program as you wish, for any purpose.
- The freedom to study how the program works, and change it so it does your computing as you wish.
- The freedom to redistribute copies so you can help others.
- The freedom to distribute copies of your modified versions to others.

** Text, Images and Data
The text, images and data are licensed under Creative Commons (BY-NC-SA). This license enables reusers to distribute, remix, adapt, and build upon the material in any medium or format for noncommercial purposes only, and only so long as attribution is given to the creator. If you remix, adapt, or build upon the material, you must license the modified material under identical terms. CC BY-NC-SA includes the following elements:

- BY: credit must be given to the creator.
- NC: Only noncommercial uses of the work are permitted.
- SA: Adaptations must be shared under the same terms.
